# -*- coding: utf-8 -*-
"""pandas17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kdVIkVZlhMvANvns-gKT8odefrG5lEC
"""

import numpy as np
import pandas as pd

"""# Create DataFrame"""

# using list
student_data = [
    [100, 80, 10], # each row
    [90, 70, 7],
    [120, 100, 14],
    [80, 50, 2]
]

pd.DataFrame(student_data, columns=['iq', 'marks','package'])

# using dict
student_dict = {
    'iq' : [100, 90, 120, 80], # each column
    'marks' : [80, 70, 100, 50],
    'package' : [10, 7, 14, 2]
}
student = pd.DataFrame(student_dict)
student

# using read_csv
movies = pd.read_csv('/content/sample_data/movies.csv')
movies.head(3)

ipl = pd.read_csv('/content/sample_data/ipl-matches.csv')
ipl.head(3)

"""# Dataframe Attributes and methods"""

# shape
movies.shape

#dtypes
movies.dtypes

# index
movies.index

# columns
movies.columns

ipl.columns

student.columns

# values
student.values

ipl.values

# head and tail
ipl.head(2)

movies.tail(2)

# sample -> to select random columns from the table
ipl.sample(2) # no of element need as a parameter

# info
movies.info()

# describe
movies.describe()

# isnull
ipl.isnull().sum()

# duplicated
movies.duplicated().sum()

# rename
student

student.rename(columns={'marks': 'percent', 'package':'lpa'}, inplace = True)

student

"""# Maths method"""

# sum -> axis alignment
student.sum() # sum each columns

student.sum(axis = 1) # row-wise sum

student.min()

student.max()

student.mean()

student.std(axis = 1)

"""# Selecting cols from a DataFrame"""

type(movies['title_x']) # each columns behave as series

# fetch multiple columns

movies[['title_x', 'title_y']] # if we extract multiple columns then it will be consider as DataFrame

ipl[['Team1', 'Team2', 'WinningTeam']]

"""# Selecting Rows from DataFrame
  - iloc : searches using index positions
  - loc : searches using index labels

 ## iloc : [start, end, stepsize] here end is exclusive
 ## loc : [start, end, stepsize] here end is inclusive
"""

student_dict = {
    'name':['Aditya', 'Akash', 'Samarth','Shreys'],
    'iq' : [100, 90, 120, 80], # each column
    'marks' : [80, 70, 100, 50],
    'package' : [10, 7, 14, 2]
}
students = pd.DataFrame(student_dict)
students.set_index('name', inplace = True)

students

# single row
movies.iloc[5] # fetching  single row

# multiple rows
movies.iloc[2:10:2] # [start, end, step]

# fancy indexing
movies.iloc[[0, 2, 3]]

# loc -> fetches based on location
students

students.loc['Akash']

students.loc['Aditya':'Samarth']

students.loc[['Samarth','Shreys']]

"""## Selecting both rows and columns"""

movies.iloc[0:3, 0:3]

movies.loc[0:2 , 'title_x':'poster_path']

"""## Filtering DataFrame"""

ipl.head(2)

# find all the final winners
mask = ipl['MatchNumber'] == 'Final' # condition
new_df = ipl[mask]                   # extracting rows
new_df[['Season', 'WinningTeam']]    # extracting col using fancy index

# combined of three above three lines
ipl[ipl['MatchNumber'] == 'Final'][['Season','WinningTeam']]

# how many super over finishes have occured
ipl[ipl['SuperOver'] == 'Y'].shape[0] # shape[0] gives rows

# how many matches has csk won in kolkata
ipl[(ipl['City'] == 'Kolkata') & (ipl['WinningTeam'] == 'Chennai Super Kings')].shape[0] # for boolean value we should use logical operation &, |

# toss winner is match winner in percentage
(ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0] / ipl.shape[0]) * 100

# movies with higher than 8 and votes > 10000
movies.columns

movies[(movies['imdb_rating'] > 8 )& (movies['imdb_votes'] > 10000)].shape[0]

"""### Very important question"""

# Action movies with rating higher than 7.5
movies.sample(2) # As we can see [genres includes multiples values in each row]
mask1 = movies['genres'].str.split('|').apply(lambda x : 'Action' in x)
# mask1 = movies['genres'].str.contains('Action') behaves same
mask2 = movies['imdb_rating'] > 7.5
movies[mask1 & mask2]

# write a function that can return the track record of 2 teams against each other

"""## Adding new Columns'"""

movies['Country'] = 'India'

movies.head(2)

movies.dropna(inplace=True)

# method to create a columns based on existing column
movies['lead actor'] = movies['actors'].str.split('|').apply(lambda x : x[0]) # .str convert object into string

movies.sample(3)

"""# Important DataFrame Functions"""

# astype()
ipl.info()

ipl['ID'] = ipl['ID'].astype('int32')
ipl.info()

# categorical datatype conversion -> applying for objects
ipl['Season'] = ipl['Season'].astype('category')
ipl.info()

ipl['Team1'] = ipl['Team1'].astype('category')
ipl['Team2'] = ipl['Team2'].astype('category')
ipl.info()

# value_counts

# find which player has won most potm -> in finals and qualifiers

# Toss decision plot

# how many matches each team has played

# sort_values -> ascending -> na_position -> inplace -> multiple cols

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/movies.csv')
df.head(2)

import pandas as pd
import numpy as np

#astype
df = pd.read_csv('/content/drive/MyDrive/datasets/movies.csv')
df.head(2)

df.describe()

df.dtypes

import sys
sys.getsizeof(df)

df['is_adult'] = df['is_adult'].astype('category')

df.dtypes

sys.getsizeof(df)

df['actors'] = df['actors'].astype('string')

df

# between
vk = pd.read_csv('/content/drive/MyDrive/datasets/kohli_ipl.csv')

vk.head(2)

vk[vk['runs'].between(51, 99)].shape[0]

# clip
subs = pd.read_csv('/content/drive/MyDrive/datasets/subs.csv')

subs.clip(100, 200) # numbers less than 100 become 100 and greater than 200 becomes 200 and inbetween remains same

# drop_duplicates
temp = pd.Series([1, 1, 1, 3, 3, 5, 6])
temp.drop_duplicates(keep='last').shape[0] #if we first to keep last occurance only the use  drop_duplicates(keep='last')

temp.unique().size

# duplicated
temp.duplicated().sum()

# isnull
temp1 = pd.Series([1, 2, np.nan, 4, 5, np.nan, 9, 11])
temp1

temp1.size

temp1.count() # it does not count null values

temp1.isnull().sum()

# dropna
temp1.dropna().size

# fillna
temp1.fillna(temp1.mean())

# isin

 # check the existence of multiple elements
vk[( vk['runs'] == 49 )| (vk['runs'] == 99)]

vk[vk['runs'].isin([49, 99])]

# apply
# used for custom logic
vk

ipl = pd.read_csv('/content/drive/MyDrive/datasets/ipl-matches.csv')
ipl.head(2)

ipl['Nickname'] = ipl['Player_of_Match'].astype(str).apply(lambda x : x.split()[-1])

ipl.info()

ipl.sample(2)

ipl['Margin'].fillna(np.mean(ipl['Margin']))

# copy

